sudo: required
language: c
dist: xenial

# using anchor to import sources into linux builds
addons:
  apt: &apt
    sources:
      - ubuntu-toolchain-r-test

# important for allowed-to-fail matching
# see https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail
env:
  - ALLOWED_TO_FAIL=0

# travis currently does not support directly setting gcc/clang with versions
# (e.g. gcc-4.8) as value for the compiler key. So we will have to manually
# request these packages and use environment varibles to create the matrix.
matrix:
  include:
    - name: "gcc-5 on Linux"
      compiler: gcc
      addons:
        apt:
          <<: *apt
          packages:
            - libsubunit-dev

    - name: "gcc-5 on Linux, Rust enabled"
      compiler: gcc
      env:
        - RUST_ENABLED=1
      addons:
        apt:
          <<: *apt
          packages:
            - libsubunit-dev

    - name: "clang-5 on Linux, Rust enabled"
      env: RUST_ENABLED=1 CC=clang-5
      script:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main" | sudo tee -a /etc/apt/sources.list
        - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/ppa
        - sudo apt-get update
        - sudo apt-get install linux-headers-`uname -r`
        - sudo apt-get --yes install bison build-essential cmake flex git libclang-common-5.0-dev libelf-dev libllvm5.0 libz-dev lldb-5.0 llvm-5.0 llvm-5.0-dev llvm-5.0-runtime
        - ./ci/run.sh

    - os: osx
      osx_image: xcode10.1
      compiler: clang

  allow_failures:
    - os: osx
      osx_image: xcode10.1
      compiler: clang

before_install:
  - ./ci/before-install.sh

script:
  - ./ci/run.sh
