
[workspace]
members = [
    "deps/ccommon/rust/cccommon-sys",
    "deps/ccommon/rust/ccommon-rs",
    "deps/ccommon/rust/ccommon-derive",
    "src/server/pingserver-rs",
    "src/server/twemcache-http",
    "src/storage/cdb/cdbgen",
    "src/storage/cdb/cdb_rs",
    "src/rust-util/httpencode",
    "src/rust-util/pelikan",
    "src/rust-util/pelikan-sys",
    "src/rustcore",
    "src/server/pingserver-rs",
    "src/storage/cdb/cdbgen",
    "src/storage/cdb/cdb_rs",
    "test/server/pingserver-rs",
    "test/server/twemcache-http"
]

[profile.release]
debug = true
lto = true
codegen-units = 1
