[package]
name = "segcache"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "a segment-structured in-memory cache with eager expiration"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[features]

# enable functions to dump JSON formatted state to disk for analysis
dump = ["serde", "serde_json"]

# enables setting/checking magic strings
magic = []

# metafeatures
debug = ["magic", "dump"]

# default set of enabled features
default = []

[dependencies]
ahash = "0.7.2"
metrics = { path = "../../rust/metrics" }
rand = { version = "0.8.3", features = ["small_rng", "getrandom"] }
rand_xoshiro = { version = "0.6.0" }
rand_chacha = { version = "0.3.0" }
rustcommon-logger = { git = "https://github.com/twitter/rustcommon" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }
thiserror = "1.0.24"
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0.64", optional = true }

[dev-dependencies]
criterion = "0.3.4"
