[package]
name = "pelikan_pingserver_rs"
version = "0.0.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "an over-engineered ping server written in Rust"
license = "Apache-2.0"

[lib]
name = "pelikan_pingserver_rs"
path = "src/lib.rs"
doc = true

[[bin]]
name = "pelikan_pingserver_rs"
path = "src/main.rs"
doc = false

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = false

[[bench]]
name = "benchmark"
path = "benches/benchmark.rs"
harness = false

[dependencies]
chrono = "0.4.11"
config = { path = "../../rust/config" }
log = { version = "0.4.8", features = ["std"] }
mio = { version = "0.7.0", features = ["os-poll", "tcp"] }
rustcommon-buffer = { git = "http://github.com/twitter/rustcommon" }
rustcommon-logger = { git = "http://github.com/twitter/rustcommon" }
rustcommon-metrics = { git = "http://github.com/twitter/rustcommon" }
rustls = "0.18.1"
slab = "0.4.2"
strum = "0.20.0"
strum_macros = "0.20.1"

[dev-dependencies]
criterion = "0.3"
