daemonize = false

[admin]
port = "9999"

[server]
# interfaces listening on
host = "0.0.0.0"
# port listening on
port = "12321"
# epoll timeout in milliseconds
timeout = 100
# epoll max events returned
nevent = 1024

[worker]
# epoll timeout in milliseconds
timeout = 100
# epoll max events returned
nevent = 1024
# number of worker threads
threads = 1

# storage configuration
[segcache]
# hash power adjusts how many items can be held in the hashtable
hash_power = 16
# total bytes to use for item storage - 4GiB
heap_size = 4294967296
# size of each segment in bytes - 1MiB
segment_size = 1048576
# eviction policy is segment random, similar to slab random for Twemcache
eviction = "Random"

[time]
time_type = "Memcache"

[buf]

[debug]

[sockio]

[tcp]

[tls]