daemonize = false

[admin]
port = "9999"

[server]
# interfaces listening on
host = "0.0.0.0"
# port listening on
port = "12321"
# epoll timeout in milliseconds
timeout = 100
# epoll max events returned
nevent = 1024

[worker]
# epoll timeout in milliseconds
timeout = 100
# epoll max events returned
nevent = 1024
# number of worker threads
threads = 1

[seg_cache]
# hash power
hash_power = 22
# size of each segment in bytes
seg_size = 1048576
# number of segments
segments = 4096
# eviction policy
eviction = "Random"

[time]
time_type = "Memcache"

# NOTE: not currently implemented
[buf]

# NOTE: not currently implemented
[debug]

# NOTE: not currently implemented
[sockio]

# NOTE: not currently implemented
[tcp]

[tls]
# certificate chain used to validate client certificate
certificate_chain = "../root.chain"
# server certificate
certificate = "../server.crt"
# server private key
private_key = "../server.key"
