[package]
name = "storage"
version = "0.0.1"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
description = "a collection of storage types for use in Pelikan backends"
homepage = "https://pelikan.io"
repository = "https://github.com/twitter/pelikan"
license = "Apache-2.0"

[dependencies]
config = { path = "../../rust/config" }
protocol = { path = "../../rust/protocol" }
rustcommon-time = { git = "https://github.com/twitter/rustcommon" }
segcache = { path = "../../storage/segcache" }