on:
  push:
    branches: [ master, SegcacheExp ]
  pull_request:
    branches: [ master, SegcacheExp ]

env:
  CARGO_TERM_COLOR: always
  MAKEFLAGS: -j 2

jobs:
  linux:
    name: bionic / gcc-7
    runs-on: ubuntu-18.04
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/run.sh
  linux_rust:
    name: bionic / cargo build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/cargo.sh
  linux_fuzz:
    name: bionic / cargo fuzz
    runs-on: ubuntu-18.04
    env:
      CC: gcc
      RUST_ENABLED: 1
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/cargo-fuzz.sh
  macos:
    name: macos / clang
    runs-on: macos-10.15
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - name: Run
      continue-on-error: true
      run: bash ci/run.sh
  macos_rust:
    name: macos / clang / cargo build
    runs-on: macos-10.15
    env:
      CC: clang
      RUST_ENABLED: 1
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: bash ci/cargo.sh
