on:
  push:
    branches: [ master, SegcacheExp ]
  pull_request:
    branches: [ master, SegcacheExp ]

env:
  CARGO_TERM_COLOR: always
  MAKEFLAGS: -j 2

jobs:
  linux:
    name: bionic / gcc-7
    runs-on: ubuntu-18.04
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/run.sh
  linux_rust:
    name: bionic / rust
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/cargo.sh
  fuzz_protocol_memcache:
    name: fuzz protocol/memcache
    runs-on: ubuntu-18.04
    env:
      CRATE_DIR: src/rust/protocol
      FUZZ_TARGET: memcache
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/cargo-fuzz.sh
  fuzz_protocol_admin:
    name: fuzz protocol/admin
    runs-on: ubuntu-18.04
    env:
      CRATE_DIR: src/rust/protocol
      FUZZ_TARGET: admin
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: bash ci/before-install.sh
    - name: Run
      run: bash ci/cargo-fuzz.sh
  macos:
    name: macos / clang
    runs-on: macos-10.15
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - name: Run
      continue-on-error: true
      run: bash ci/run.sh
  macos_rust:
    name: macos / rust
    runs-on: macos-10.15
    env:
      CC: clang
      RUST_ENABLED: 1
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: bash ci/cargo.sh
