[package]
name = "metrics"
version = "0.1.0"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustcommon-fastmetrics = { git = "https://github.com/twitter/rustcommon" }
strum = "0.20.0"
strum_macros = "0.20.1"